# Generated by Django 3.0.8 on 2020-07-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha modificación')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='nombre')),
                ('nationality', models.CharField(max_length=64, verbose_name='nacionalidad')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha modificación')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='título')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.Author', verbose_name='autor')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
            },
        ),
    ]
